// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgnzkxgqhtdmqkduefxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnbnpreGdxaHRkbXFrZHVlZnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NjIyNTEsImV4cCI6MjA1NTAzODI1MX0.2Tt0O7JHHgJlTBvcIxEBmkMeItEs0djHymgM5F0HnW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);